lint.ignore = [
    "E203", "E226", "E228", "N802", "N803", "N806", "N812", "N813", "N815", "N816"
]
line-length = 110
exclude = ["__init__.py"]
lint.select = ["E", "F", "I", "N", "W"]
[lint.pycodestyle]
max-doc-length = 110
[lint.pydocstyle]
convention = "numpy"
